### ISSUE TITLE
Scooter - Stat DAG Fail -  No Space Left on Device

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/aqueduct#113]
@RMK0110 can you tag a look at some of the DAG run logs? [this](https://stackoverflow.com/questions/29602409/could-not-write-to-hash-join-temporary-file-no-space-left-on-device) might be a lead

**Comment by ian-r-rose** [comment]
Also worth investigating: https://aws.amazon.com/premiumsupport/knowledge-center/diskfull-error-rds-postgresql/
