### ISSUE TITLE
ETL SANSTAR Datasets

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/aqueduct#132]
currently, BOS is providing some data from teh SANstar system as arcgis feature servers. Let's get into Postgres so we can analyze / dashboard.

**Comment by brendanbailey** [comment]
I'm having trouble accessing the feature servers via the rest api.

There rest api instructions require me to set up an account with Postman, but that service isn't functioning as described in the docs (https://developers.arcgis.com/labs/rest/get-an-access-token/)

Do you have recommendations or sample code on how you access the data from these?

Alternatively, I could ask Oscar to share the layers with my account and then I could use the ArcGIS python library to access them.

**Comment by brendanbailey** [comment]
@hunterowens @ian-r-rose 

So I'm close to creating the dags for the SanStar data. I tried creating separate tables for the Code 55 and Code 75 data, but I have insufficient privileges.

Could you create those tables for me?
CREATE TABLE "public-health"."Code55" (
	index BIGINT, 
	"Id" BIGINT, 
	"GlobalID" TEXT, 
	"Number" TEXT, 
	"AssociatedServiceRequestNumber" TEXT, 
	"DateCreated" TIMESTAMP WITHOUT TIME ZONE, 
	"DateApproved" TIMESTAMP WITHOUT TIME ZONE, 
	"ExpirationDate" TIMESTAMP WITHOUT TIME ZONE, 
	"Status" BIGINT, 
	"Address" TEXT, 
	"City" TEXT, 
	"ZipCode" TEXT, 
	"CrossStreet" TEXT, 
	"CouncilDistrict" TEXT, 
	"APREC" TEXT, 
	"LocationComments" TEXT, 
	"SubmittedBy" TEXT, 
	"ReportingPerson" TEXT, 
	"RPContactNo" TEXT, 
	"Details" TEXT, 
	"HEAssessmentBy" TEXT, 
	"AssessmentContactNo" TEXT, 
	"HEAssessmentDetails" TEXT, 
	"AssessmentLocationDescription" TEXT, 
	"AnchorPhotos" TEXT, 
	"DateCompleted" TIMESTAMP WITHOUT TIME ZONE, 
	"CleanupDate" TIMESTAMP WITHOUT TIME ZONE, 
	"CompositeID" TEXT, 
	"DataSetName" TEXT
)

CREATE TABLE "public-health"."Code75" (
	index BIGINT, 
	"OBJECTID" BIGINT, 
	address TEXT, 
	cd FLOAT(53), 
	closeddate TEXT, 
	createddate TEXT, 
	latitude FLOAT(53), 
	longitude FLOAT(53), 
	reasoncode BIGINT, 
	resolutioncode TEXT, 
	srnumber TEXT, 
	status TEXT
)

**Comment by ian-r-rose** [comment]
@brendanbailey Thanks! Can you add the table creation code in your script (probably with an `IF NOT EXISTS` clause)? We can then test it in the `docker-compose` environment before deploying to production. The test environment has a postgres analytics db networked in, so it should behave more-or-less the same.

**Comment by ian-r-rose** [comment]
Fixed by #134, thanks again @brendanbailey
