### ISSUE TITLE
Convert `JSON` fields in PostGIS to `geometry` fields. 

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/aqueduct#16]
PostGIS supports a Geometry type. We should add a view that has the geometry and a foreign key to the original tables that have Geographical information. 

[This method](https://postgis.net/docs/ST_GeomFromGeoJSON.html) from the documentation may be helpful. 

I suspect this will be a `SELECT UPDATE` query.

**Comment by hunterowens** [comment]
This is for the waze data, FYI.

**Comment by bryanblackford** [comment]
Added PostGIS to db. Created geotable with a row of geometry per each AJI record.

**Comment by hunterowens** [comment]
Great!

**Comment by hunterowens** [comment]
Can you commit the code somewhere?
