### ISSUE TITLE
Public Data for Searchable Map

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/aqueduct#162]
Request from EMD to setup a searchable map for residents to view 

1) [LAUSD Grab and Go Centers](https://www.google.com/maps/d/u/0/viewer?mid=1_R_MQhVYaKh3A5_8oAtOtlNK2XWjzP2t&ll=34.00362679120255%2C-118.38496199999997&z=10) 
2) Hand Washing Stations (see email) 
3) More data TK.

**Comment by hunterowens** [comment]
(map could then be embed into various sites via web services)

**Comment by hunterowens** [comment]
@laitawebservices  reports that iframe embed is preferable for the websites. [example](https://www.lacity.org/support-for-residents)

**Comment by hunterowens** [comment]
[Possible Searchable Map Templates](https://github.com/datamade/searchable-map-template-csv)

**Comment by hunterowens** [comment]
[Carto Version](https://github.com/datamade/searchable-map-template-csv)

**Comment by hunterowens** [comment]
@tiffanychu90 can you link the ESRI 311 map you did?

**Comment by tiffanychu90** [comment]
311 search tool: http://lahub.maps.arcgis.com/apps/webappviewer/index.html?id=ebaa249faa994f8ea44bcb6859278cab

**Comment by ian-r-rose** [comment]
Some thoughts on different searchable map options:

## Google My Maps
#### Pros
1. Relatively easy to use, no-coding required
1. Good site reliability, unlikely to go down
1. Familiar
1. Easy to iframe
1. Can handle multiple layers

#### Cons
1. Less flexible than some other options
1. Probably more manual labor to keep layers up-to-date (no one-command deploy)
1. Not clear if we could add any temporal element to the layers

## ESRI

#### Pros
1. Familiar CLI for updating layers
1. Easy to iframe
1. Can handle multiple layers

#### Cons
1. Is their geocoding/searching up to the task?
1. Not very flexible

## Datamade searchable map template
#### Pros
1. Very flexible
1. Can statically host wherever we want (S3, GH pages)
1. Easy to make updates via scripts
1. Nice geocoding/searching built in.

#### Cons
1. Have to figure out static hosting
1. Some coding required
1. Maybe have to figure out how to add multiple layers.

**Comment by JeanneHolm** [comment]
L.A. neighborhood COVID-19 cases (point in time): http://www.publichealth.lacounty.gov/phcommon/public/media/mediapubhpdetail.cfm?prid=2271

**Comment by hunterowens** [comment]
Thought for now is to use myMaps for the embed layer.

**Comment by hunterowens** [comment]
On  hold pending BOE

**Comment by hunterowens** [comment]
This is completed in cityoflosangeles/public-health-prototype#39

**Comment by ian-r-rose** [comment]
Fixed by CityOfLosAngeles/public-health-prototype#39, CityOfLosAngeles/public-health-prototype#40, CityOfLosAngeles/public-health-prototype#41
