### ISSUE TITLE
Convert `store_data_file.py` to Airflow Job and schedule to run nightly

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/aqueduct#19]
@bryanblackford can you upload the store data file .py file to `dags/transportation/waze` and then can we on rewriting it using airflow to run night?

**Comment by hunterowens** [comment]
Nice work @bryanblackford. 

Can you use [Airflow Credentials](https://airflow.apache.org/configuration.html) to store and use the PostgreSQL connections rather than having to place in it in the file itself?

**Comment by bryanblackford** [comment]
This was completed months ago. The dag file is in dag-waze-dataProcessor.py and runs every minute. Credentials are stored in airflow connections.
