### ISSUE TITLE
automate Dan's chart in the mayor's dashboard

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/aqueduct#199]
It's an MSA level aggegrate, auto update the data based on the JHU data that @tiffanychu90 fixed

**Comment by tiffanychu90** [comment]
Needs to use the us_county_time_series feature layer: http://lahub.maps.arcgis.com/home/item.html?id=4e0dc873bd794c14b7bd186b4b5e74a2

**Comment by igotcharts** [comment]
I believe Dan is still using the [NY Times](https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv) for the county. They seem to be updating a bit more frequently now.

**Comment by tiffanychu90** [comment]
Our county time series used NYT up through 3/31, and from 4/1 onward, pulls JHU's feature layer, since it's not a day behind. But yes, NYT reports New York City (and Kansas City, MO) separately, not at the county-level, which would differ from JHU. 

Feel free to set up a DAG that automates pulling data from NYT GitHub. How we're cleaning NYT data is in `create-us-county-time-series.py`.

**Comment by igotcharts** [comment]
JHU reports NYC too. I'm not sure about their feature layer, but they do on these layers:

https://raw.githubusercontent.com/CSSEGISandData/COVID19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv

https://raw.githubusercontent.com/CSSEGISandData/COVID19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv

**Comment by tiffanychu90** [comment]
Ahh, you're right, JHU does, and I'm dropping it somewhere in the processing. Need to fix that.

**Comment by hunterowens** [comment]
Seems like there is an table that is uploaded to arc that isn't in the group yet but should be fairly self explanatory.

@igotcharts [FIPS TABLE](https://docs.google.com/spreadsheets/u/1/d/16dbgSRn61WmhWtZbOnDvHCExiDVEK383tEMHnvAhPWQ/edit?usp=drive_web&ouid=109664471378367396661) 

Step is to add to JHU to esri dag a second task, to generate per capita numbers and upload to esri

**Comment by tiffanychu90** [comment]
Let's adapt this crosswalk from NBER: https://data.nber.org/data/cbsa-fips-county-crosswalk.html. This resembles more of our `us_counties_time_series` schema, and we can do the merge more easily.
