### ISSUE TITLE
Add geometry to geoTable when adding Waze data

### ISSUE THREAD

**Issue by bryanblackford** [CityOfLosAngeles/aqueduct#24]
Adding the geometry in the python script would be nice, but pandas df.to_sql doesn't return the rows with the pid's that are referenced by the geoTable. 

My current solution is an SQL Trigger which inserts the geometry on insert to the a/j/i table.

**Comment by hunterowens** [comment]
Nice, thank makes sense.

**Comment by bryanblackford** [comment]
Triggers are now active on datalake.waze (and waze2, the testing schema). Created with waze/waze-geo-trigger.sql.
