### ISSUE TITLE
Fix Socrata Connection 

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/aqueduct#240]

**Comment by hunterowens** [comment]
updated credentials @sherryshenker can you test?

**Comment by sherryshenker** [comment]
Yes. it appears to be working [here](https://platform.civisanalytics.com/spa/#/scripts/containers/71512969). Thank you! I'll look into what the cleaning scripts are that we can transfer now that we have the raw data

**Comment by sherryshenker** [comment]
@hunterowens  just noticed that the public health dashboard also relies on another data set.  `tbl(con,` dbplyr::in_schema('"public-health"','"cleanstat"'))` does that also live in socrata?

**Comment by hunterowens** [comment]
@sherryshenker that table is created in [this](https://github.com/CityOfLosAngeles/aqueduct/blob/master/dags/public-health/care-311-to-postgres.py) script

**Comment by sherryshenker** [comment]
I think I'm missing something. is `cleanstat` different from `311-cases-homelessness`. I only see where the latter is created.

**Comment by hunterowens** [comment]
Yeah - cleanstat is an LASan program where they measure the cleanliness of the streets on a 1-3 scale done each quarter, while 311-cases-homeless is a subset of 311 service request types that are related to homelessness.

**Comment by sherryshenker** [comment]
got it. is there a socrata dataset ID for that data? I'm not seeing it in the script you linked.

**Comment by hunterowens** [comment]
Yep. See [link](https://github.com/CityOfLosAngeles/aqueduct/blob/fd24c3ceb40d192bc07030adbe8bc128f0f7894b/dags/public-health/care-311-to-postgres.py#L19

**Comment by sherryshenker** [comment]
alright, im definitely missing something, I thought that was the ID for `311-cases-homelessness`

**Comment by hunterowens** [comment]
hrrmmm. 

Two datasets get loaded into the public health schema, but only one (311-cases-homeless) is need for the Shiny dashboard to run

**Comment by sherryshenker** [comment]
[This](https://github.com/snassef/public-health-prototype/blob/7a4005b078186c3b1479427787763f4e6e7f7e1c/dashboard/load_data.R#L117) is where i'm seeing the second data set referenced. the 311-cases-homeless is loaded earlier [here](https://github.com/snassef/public-health-prototype/blob/7a4005b078186c3b1479427787763f4e6e7f7e1c/dashboard/load_data.R#L59)

**Comment by hunterowens** [comment]
Oh right. Since the cleanstat data is only updated quarterly, we just had a quick downloader notebook. 

[link](https://github.com/snassef/public-health-prototype/blob/master/notebooks/Cleanstat-Downloader.ipynb)

**Comment by sherryshenker** [comment]
I think this is done? @hunterowens

**Comment by hunterowens** [comment]
Great! Closing
