### ISSUE TITLE
Add overall aggregates in RAP Shelter email

### ISSUE THREAD

**Issue by ian-r-rose** [CityOfLosAngeles/aqueduct#249]
Per Brian Buchner's request, add some top-level numbers to the email:

* Total beds+trailers occupied
* Total beds+trailers available
* Total beds occupied
* Total beds available
* Total trailers occupied
* Total trailers available

**Comment by hunterowens** [comment]
Thanks. I can take a look at this if you'd like @ian-r-rose

**Comment by ian-r-rose** [comment]
Sounds good

**Comment by ian-r-rose** [comment]
Should also probably include safe parking and isolation programs
