### ISSUE TITLE
Import all of 311 in Redshift

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/aqueduct#254]
In socrata. 

Dataset ID: `aub4-z9pc`

**Comment by hunterowens** [comment]
ref #255

**Comment by sherryshenker** [comment]
@hunterowens did you want to do this yourself or have us do this? you should be able to clone [this script](https://platform.civisanalytics.com/spa/#/scripts/containers/71512969)  and edit the dataset ID and table parameters to run. However, I think once we have everything with the LA  "robot user" set up, we should change to have a template script that you use, instead of cloning the container

**Comment by hunterowens** [comment]
@sherryshenker 
![image](https://user-images.githubusercontent.com/1735650/80614618-85055980-89f3-11ea-83f2-cc90e10d3324.png) robot is invited!

**Comment by sherryshenker** [comment]
@hunterowens  do you usually read this data in all at once, or do incremental loads? I'm running into a timeout error [here](https://platform.civisanalytics.com/spa/#/scripts/custom/73966020)

**Comment by sherryshenker** [comment]
Nevermind, I was able to move the data over in a few chunks. So now we need to set up the pipeline to do the incremental inserts. Could you move this ticket to "in progress"?

**Comment by hunterowens** [comment]
@akoebs @snassef to rewrite import to use multiprocessing, and follow on PR with version that removes the table and replaces

**Comment by hunterowens** [comment]
How to download the entire [dataset in curl](https://github.com/CityOfLosAngeles/aqueduct/blob/3f74874efebbcd2cf4b21e4165bd9728cac4a9aa/dags/myla311/download-data.sh#L7)

**Comment by akoebs** [comment]
@hunterowens  we have set-up the import and the entire 311 set lives in public.import311data.  We have the import running every 3 days or so. Do you want us to submit a PR to Aqueduct prior to moving/closing this issue?

**Comment by hunterowens** [comment]
@akoebs yeah, let's have a PR with that and then clkose.

**Comment by ian-r-rose** [comment]
@akoebs Did the 311 import code ever make its way over here? Or in version control somewhere?

**Comment by hunterowens** [comment]
this is completed!
