### ISSUE TITLE
Key indicators dataset

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/aqueduct#271]
Break out to LACounty, LACity. Produce a key indicator dataset of what are the key metrics, publish a a JSON blob 

| Type | Date | Geography Available | Indictor_num | Number_3_day_avg | Number_7_day_avg |
| ----- | ----- | --------------- | ---------------- | ------------------------ | ---------------------------|
|`cases`| 2020-05-05 | LACity and LACounty | 2,000 |  1,500 | | | 
| `deaths` |2020-05-05 | LACity and LACounty |  
|`virus_tests_per_1k` | 2020-05-05 | LACity only?
|`hospitalizations` | 2020-05-05 | LACounty only? Not sure

**Comment by hunterowens** [comment]
In order to make this as platform agnostic as possible, the idea would be to produce / clean the data, and the dump a `pd.to_json()` JSON blob to an S3 bucket with public access. @igotcharts / @brendanbailey  can you confirm that that would work with Tableau?

**Comment by igotcharts** [comment]
Not directly, but through Amazon Athena, yes.

https://www.tableau.com/about/blog/2017/5/connect-your-s3-data-amazon-athena-connector-tableau-103-71105

**Comment by hunterowens** [comment]
ah interesting. Can you not supply an `http:` scheme for the [JSON Connector](https://help.tableau.com/current/pro/desktop/en-us/examples_json.htm)

**Comment by hunterowens** [comment]
seems like this doesn't need support from ITA, @igotcharts is using Google sheets on the backend.
