### ISSUE TITLE
resolve and document DB permissions errors

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/aqueduct#285]

**Comment by hunterowens** [comment]
@ian-r-rose to test fix.

**Comment by hunterowens** [comment]
@ian-r-rose can you write up the closing documentation for this?

**Comment by ian-r-rose** [comment]
This has been resolved by creating an `ita-data` group in both databases and giving it CRUD permissions on them. Civis recommends following fairly standard permissions policies on the DB instances. Per @juliaoran :

> Individual users who own tables will have to grant permissions on those tables (ie. if the robot owns a table and you want to be able to see it as yourself, you will have to assume the robot role, grant yourself, and then resume your role). All users of Platform can use the SQL query pane to grant users permissions on the tables they create. Typical commands include:

>>    GRANT SELECT ON TABLE table_name TO user (read permissions)
    GRANT ALL on TABLE table_name TO user (all permissions)
    You can find additional documentation on the GRANT command here.

> By default, tables a user creates are only visible to that specific user. If you wish to change this, you can alter the default privileges by following the documentation here (ie. all tables created by the robot are visible to the ita_data group). 

> As far as best practices, we recommend granting permissions by group rather than individual, and as the number of users on the cluster grows this will become especially valuable, and we can discuss how to further segment users. Beyond that, the general rule we follow is grant users the lowest level of permissions possible (ie. don't grant someone create privileges if they just need to be able to be able to read data from the table, just grant select permissions).
