### ISSUE TITLE
Best practices for Redshift vs Postgres

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/aqueduct#290]
@akoebs to send civis docs

**Comment by akoebs** [comment]
Working Document for the ITA team: https://docs.google.com/document/d/1Yal400JQvN7jH2V83TbS6IlzleZGo4SsQshSAKoijSs/edit?usp=sharing

**Comment by snassef** [comment]
Working Document for the ITA team: https://docs.google.com/document/d/1nBM0yB6r_IbPA1g5F9JnETv0VPxSxMpu72VDNbvBNLY/edit?usp=sharing

**Comment by ian-r-rose** [comment]
Closing as completed, thanks @akoebs and @snassef
