### ISSUE TITLE
Automating jobs at longer-than-weekly intervals

### ISSUE THREAD

**Issue by ian-r-rose** [CityOfLosAngeles/aqueduct#302]
The Civis Platform UI doesn't allow for automating jobs at longer than weekly intervals (e.g., monthly, quarterly, etc). @akoebs has indicated that it is possible to do this with the client API.

1. Is there an example somewhere that shows this functionality?
1. If one does schedule a job for weirder intervals, is this reflected in the UI somewhere?

**Comment by hunterowens** [comment]
@akoebs no particularly good solution. result to weekly or a check date condition

**Comment by ian-r-rose** [comment]
Closing as won't-fix
