### ISSUE TITLE
311 redshift table time-like values

### ISSUE THREAD

**Issue by ian-r-rose** [CityOfLosAngeles/aqueduct#304]
There are a number of columns in the 311 data that are time-like (createddate, closeddate, etc), but which currently have string datatypes.

In order to do operations like filtering by date, we must then do a potentially expensive cast. Can we update the scheduled job to get make time-like columns have the approprate datatypes?

**Comment by akoebs** [comment]
We are looking at fixing in this when we update the Socrata import so the table creates with appropriate data types based on a metadata read from Socrata.

**Comment by hunterowens** [comment]
@snassef reports that tables have been updated

**Comment by ian-r-rose** [comment]
Closing as completed
