### ISSUE TITLE
Cannot shutdown Civis notebook session

### ISSUE THREAD

**Issue by ian-r-rose** [CityOfLosAngeles/aqueduct#306]
Whenever I try to shutdown a Civis notebook session (if, e.g., I need to change the settings), it fails with the message
```
Error shutting down notebook server. An unexpected condition was encountered.
```
I tried to submit a help request through the platform help system, but the "Submit a request" dialog in zendesk was broken for me, with an empty dropdown and nothing else.

**Comment by ian-r-rose** [comment]
The first issue appears to be solved by waiting for a few minutes for the notebook server to be culled by the system, then refreshing the page manually. Seems like a bug in the SPA

**Comment by hunterowens** [comment]
todo: email support@civisanalytics.com

**Comment by ian-r-rose** [comment]
The product team has deployed a fix for this issue.
