### ISSUE TITLE
Civis Jupyter extensions force old pandas

### ISSUE THREAD

**Issue by ian-r-rose** [CityOfLosAngeles/aqueduct#307]
The Civis Jupyter extensions package forces an old version of pandas when you install it: https://github.com/civisanalytics/civis-jupyter-extensions/blob/64cf97f3d24218e17088dcae33a14e765b11c662/requirements.txt#L2

The most recent version of pandas is 1.0. This is not necessarily a huge problem, except when you follow the instructions for setting up a custom docker image given [here](https://civis.zendesk.com/hc/en-us/articles/115004754546-Notebooks-and-Docker-Images). This overrides any pandas specification given earlier in the docker image.

We can get around this by later upgrading the pandas version, as I have done in our custom image [here](https://github.com/CityOfLosAngeles/aqueduct/blob/0d03bdf119f5585572a6b708acf9f98621e2fbd1/civis/Dockerfile#L117-L119), but I feel like this shouldn't be necessary. Would it be possible to remove this restriction?

**Comment by ian-r-rose** [comment]
Cf. https://github.com/civisanalytics/civis-jupyter-extensions/pull/9

**Comment by hunterowens** [comment]
@akoebs still waiting on answer from civis tech team

**Comment by mikesaelim** [comment]
Hi all, you should be able to use pandas 1.x with the [latest version of civis-jupyter-notebook, v2.0.0](https://github.com/civisanalytics/civis-jupyter-notebook/releases/tag/v2.0.0).  Let me know if it doesn't work or if you have any questions!

**Comment by ian-r-rose** [comment]
Thanks for the update @mikesaelim !
