### ISSUE TITLE
Automatically build and take citywide-civis-lab - latest image from master using gh actions 

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/aqueduct#309]

**Comment by ian-r-rose** [comment]
I would very much like to see this. @hunterowens have you played with docker image build/push using GH-actions?

**Comment by ian-r-rose** [comment]
Also, should we make a team dockerhub account?

**Comment by hunterowens** [comment]
@jaylenw is our resident expert on that.

**Comment by jaylenw** [comment]
@hunterowens @ian-r-rose , If my memory serves me right, Docker and Docker Compose are available in the GitHub Actions runner by default. So a simple docker login and docker push command should work. Just store your personal access token for the registry in the secrets of your GitHub repo. As far as a dockerhub account, I thought in addition to that, a City of Los Angeles organization on DockerHub?

An even easier option is to use this open source action to push to Docker Hub, https://github.com/marketplace/actions/publish-docker.

Here is an example with one of my personal projects for build and push using that action, https://github.com/jaylenw/nota/blob/0f28b5e07e8dfe31507abfb6a4077d09f5dff3d2/.github/workflows/ubuntu-build.yml

**Comment by hunterowens** [comment]
@jaylenw Ty for the examples. We've merged a version that does this (see #310) 

Closing for now.

**Comment by jaylenw** [comment]
@hunterowens @ian-r-rose Awesome!
