### ISSUE TITLE
Data warehouse catalog service

### ISSUE THREAD

**Issue by ian-r-rose** [CityOfLosAngeles/aqueduct#320]
It would be nice to share a view into the civis data warehouse tables using a service so that external stakeholders could easily inspect it. Not the actual data, but maybe the available tables and some metadata.

**Comment by ian-r-rose** [comment]
Looked into this yesterday, and I think we might be overthinking it. I had some success creating Panel/ipywidgets-based GUIs that showed the data tables to the user. However they were somewhat annoying to use since they involved several requests to the database backend, each of which had several seconds of overhead. Combine this with any k8s pod startup time, and it winds up being quite some time before the user sees any content. Now, I could probably reduce the number of requests to the backing databases by putting together a more complex query, but I think there would be diminishing returns.

The content is, at the end of the day, a not-very-dynamic view of some tabular data. What if instead of a live service, we scheduled a job that made a nice static HTML file? This could be hosted on gh-pages like anything else. It could even have some light interactivity with offline ipywidgets.

**Comment by hunterowens** [comment]
yeah, I think that also makes sense. explaining it on the call yesterday made me realize this is _much_ simpler than I thought.
