### ISSUE TITLE
Deprecate COVID layers on ESRI

### ISSUE THREAD

**Issue by tiffanychu90** [CityOfLosAngeles/aqueduct#321]
Changes, decide whether to deprecate ESRI layer or update Aqueduct DAG:
- [x]  [COVID tests conducted](https://lahub.maps.arcgis.com/home/item.html?id=64b91665fef4471dafb6b2ff98daee6c): Google spreadsheet changes mean this [script](https://github.com/CityOfLosAngeles/aqueduct/blob/master/dags/public-health/covid19/sync-covid-testing-data.py) is out of date

No changes (to be deprecated 7/22)
- [x] [Cases in City of LA](https://lahub.maps.arcgis.com/home/item.html?id=1d1e4679a94e43e884b97a0488fc04cf)
- [x] [Hospital bed/equipment layer](https://lahub.maps.arcgis.com/home/item.html?id=956e105f422a4c1ba9ce5d215b835951)
- [x] [JHU US county time-series](https://lahub.maps.arcgis.com/home/item.html?id=8f13bb3abefe490f9edd47df89664b56)
- [x] [JHU global time-series](https://lahub.maps.arcgis.com/home/item.html?id=20271474d3c3404d9c79bed0dbd48580) and [current date](https://lahub.maps.arcgis.com/home/item.html?id=191df200230642099002039816dc8c59)
- [x] [MSA comparison](https://lahub.maps.arcgis.com/home/item.html?id=b37e229b71dc4c65a479e4b5912ded66)

**Comment by tiffanychu90** [comment]
@prestinomills Noticed some changes in the spreadsheet that affect the COVID testing layer. Can you decide whether you'd like to provide an update to the DAG, or if the ESRI layer is unused, we can deprecate this layer? Since the ESRI layer is now showing incorrect info, we're at a decision point. Most COVID ESRI layers aren't impacted, though as changes arise, they'll be moved from "No changes" to "Changes"

**Comment by hunterowens** [comment]
sent email, no changes to be removed on 7/22

**Comment by hunterowens** [comment]
@ian-r-rose can you make a PR remove all the DAGs?

**Comment by ian-r-rose** [comment]
Sure
