### ISSUE TITLE
Transferring ownership of jobs to the robot user

### ISSUE THREAD

**Issue by ian-r-rose** [CityOfLosAngeles/aqueduct#325]
We have been working out how our typical dev workflow will work. In particular, we want something like a two step process:

1. Prototype a job using our user accounts, as well as our user credentials.
1. Once the job is complete, transfer ownership of that job to the robot user, where it can be scheduled/automated.

However, we have run into a few difficulties with this, partially due to the dual permissions model (platform permissions + database permissions):

* After making the robot user a manager, it still needs to switch the credentials in a script to ones that the robot owns. This seems like it works for database credentials, but as far as I have been able to tell it *does not work for other kinds of credentials*. Even worse, unless the robot owner transfers credentials, it cannot edit the parameters for a script. So you are left in a place where you cannot transfer credentials, and you cannot edit it to manually swap credentials. There may be ways around this, but it makes it quite difficult to share with another user, even though they have manager permissions.
* Many of our scripts have custom credentials that connect to third-party data services. Can these credentials be shared with the robot user? I can re-create them anew in the robot user account, but it seems like it would be nicer/less-error-prone to be able to share credentials between users. Easier to revoke or change them as well.
* The robot user still seems to be missing some crucial permissions on the underlying databases that it needs. So if I create some tables with my user account, then try to transfer the job to the robot user, it doesn't have CRUD permissions on those tables. Now, I can delete those tables with my account and then allow the robot user to create them anew, but that is not particularly ergonomic. We would prefer to allow the robot user to have CRUD permissions on most (all?) schemas by default. @hunterowens tried to add those permissions today, but he doesn't seem to have sufficient superuser permissions himself.

Any thoughts/recommendations would be appreciated. Also, please let me know if I have any of this wrong.

**Comment by ian-r-rose** [comment]
Some notes from David in the support group:
> Those are some great points/questions. Here are a few notes:
> We've heard that feedback about needing to have a shared database credential as an issue to be able to edit the parameters. We're working on making it easier to edit script inputs like that, but in the meantime, there's a workaround that works for me. You could create a new empty database credential and share it with the robot (and whatever users/groups need to share/edit jobs).  That way, when you need to share a job so someone else can edit it, you can set the database credential parameter to use that shared empty credential.

> You can share credentials between users via the Python or R API clients. Here are the endpoints to share with users and with groups.

> For data permissions, there are a few options:
        *  We can give users superuser permission, if it'd help manage grants and you're okay with the security implications (though we do NOT advise having the robot as a superuser). If you let me know which users and which cluster(s), we can help take care of it.
        * If the issue is that new tables are added to that the robot needs access to, and it's inefficient to run grants each time, ALTER DEFAULT PRIVILEGES might help. This essentially lets you say "whenever person A adds tables to schema <schemaname>​, grant ​<permissionlevel> to user/group B".
        * The other option, if you are templatizing your scripts, would be to set the user context to 'author'. This would let people run scripts from the template but use the credential of the author of the original backing script.

**Comment by hunterowens** [comment]
for now, the workaround is to re create the job as robot user. For credential sharing, need to run sharebot on credential IDs to share your credentials with Robot. 

Q3/Q4, might be able to use the sharing functionality. 

Civis folks to share deploy script that use the API to create credentials / job as robot user.
