### ISSUE TITLE
Civis Usage Report

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/aqueduct#330]
track key metrics on platform. 

* [ ] Amount of Data used
* [ ] Amount of compute used 
* [ ] num users by type 
* [ ] number of tables 
* [ ] number of scheduled scripts

**Comment by hunterowens** [comment]
open to ideas

**Comment by ian-r-rose** [comment]
Some of these we could almost certainly do with the Civis API client, though I'm also curious whether they have any pre-canned reporting around this. They must be tracking at least the amount of data and compute used.

**Comment by hunterowens** [comment]
waiting to see pre-canned civis import.

**Comment by snassef** [comment]
The more technical breakdown of compute used can be found in the "Platform Usage Overview" under the admin tab of your Platform account and here is v1 of a more executive facing report: https://platform.civisanalytics.com/spa/#/reports/84025
