### ISSUE TITLE
Socrata Import

### ISSUE THREAD

**Issue by snassef** [CityOfLosAngeles/aqueduct#331]
I am coming up on a couple issues with Socrata that I wanted to bring to your attention: 

-  For the building permit dataset, the metadata specifies columns that are no longer in the dataset. 

- The system fields concatenate to either the beginning or the end of the database depending on the dataset. 

- column names are not always congruent to metadata field names and can include spaces, apostrophes, and parentheses. 

Have you all seen these problems before? I assume that some of these issues have to do with some of the more 'legacy' datasets that Hunter mentioned in our meeting yesterday. These nuances mess with our datatype mapping. I have a solution that I am going to begin to work on, but I am worried that if datasets are working on different versions of Socrata, each version might have a challenge of its own and lead to more failures down the line. I will work on getting these fixed, and if you would all like I can add a parameter for a 'simple' import which doesn't do the datatype mapping and imports the data raw-ish for if this fails in the future.

**Comment by snassef** [comment]
Or another option is to exclude system fields: created_at, updated_at, cid

**Comment by snassef** [comment]
for now, I got a clean version of the building dataset in public.ladbs_permits!

**Comment by ian-r-rose** [comment]
@snassef do you have a link to the metadata issue, or a minimal code snippet demonstrating the problem?

**Comment by snassef** [comment]
`   
dataset_id = 'nbyu-2ha9'

raw_metadata = socrata_client.get_metadata(dataset_id, content_type="json")

results = socrata_client.get(
        dataset_id,
        limit=5,
        content_type="csv",
        exclude_system_fields=True,
        offset=0
        )

df = pd.DataFrame(results[1:], columns=results[0])

cols = []
datatypes = []

for i in np.arange(len(raw_metadata['columns'])):
        cols.append(raw_metadata['columns'][i]['name'])
        datatypes.append(raw_metadata['columns'][i]['dataTypeName'])

def diff_metadata_columns(li1, li2): 
        diff = (list(set(li1) - set(li2)))
        return diff

diff = diff_metadata_columns(cols, list(df.columns))

print(diff)
`

**Comment by ian-r-rose** [comment]
Thanks @snassef, I also see the same problem. Looks like LADBS hasn't updated the metadata for that dataset since 2016 (ADU permitting, one of the columns that is different, happened since then).

There are a few problems here, as far as I can tell:
1. LADBS not keeping the metadata up-to-date on socrata.
1. I think this is the bigger issue: Socrata really should have a better data model, given that this is their whole business. If they can't keep the list of column names in the metadata up-to-date with what columns are actually in the dataset, I'm not sure what they are spending their time doing.
1. My team members are probably tired of me saying this, but we should really stop using CSVs so much. With a better data model that actually tracked dtypes this would be a non-issue.

**Comment by ian-r-rose** [comment]
A few more thoughts on this:

>     * For the building permit dataset, the metadata specifies columns that are no longer in the dataset.

I think the best way forwards on this is to:
* Reach out to LADBS (and maybe have @prestinomills do it?) to ask them to update the metadata to reflect the current dataset, or figure out who can.
* Make this script more resilient to mismatches between metadata and data (about which more below)

>     * The system fields concatenate to either the beginning or the end of the database depending on the dataset.

I'm not sure what you mean here, can you elaborate?

>     * column names are not always congruent to metadata field names and can include spaces, apostrophes, and parentheses.

I see the metadata has both a "fieldName" and "name" fields, the latter of which can have non-JSON-identifier characters. Seems okay to me.

With regards to your idea of a "simple" import: I think the way forward might be to use the metadata in more of an advisory way. That is to say, we get the dataset from Socrata and check each column. If the metadata has that column, coerce it to the indicated type. If it does not have that column, try to infer the type on a best-effort basis.

None of this is fully satisfying, though.

**Comment by snassef** [comment]
It took some gymnastics, but i got it to work! It can handle the metadata issues present in the building permits dataset and also still works with the 311 import. I am optimistic that it will work on other Socrata datasets - maybe if you all have a list I can test them over the next few days. I am cleaning up the code and will send over PR by EOD.

**Comment by hunterowens** [comment]
@hunterowens to send list interesting / important Socrata datasets

**Comment by snassef** [comment]
PRs have been submitted.

**Comment by hunterowens** [comment]
closed in #337
