### ISSUE TITLE
Establish better permissions model for schemas

### ISSUE THREAD

**Issue by ian-r-rose** [CityOfLosAngeles/aqueduct#332]
The robot user is currently missing some CRUD permissions on schemas in both Postgres and Redshift. We should make sure that the robot user is in a group that has the relevant permissions.

From the Civis side: we would be interested in some scripts and best practices around what permission groups should exist.

**Comment by skomanduri** [comment]
@ian-r-rose We have [this article](https://civis.zendesk.com/hc/en-us/articles/115000695326#AlterDefaultPrivileges) in our knowledge base about using `GRANT` and `ALTER DEFAULT PRIVILEGES`.  The best way to manage this is to create a schema per group or per project and then have each collaborator run `ALTER DEFAULT` to share their tables within the schema.  We are planning to draft a clearer how-to guide about this.

**Comment by skomanduri** [comment]
Added some guides to our knowledge base with various options depending on how you want to organize your data and users:

- [Schema Organization](https://civis.zendesk.com/hc/en-us/articles/115000712463-Schema-Organization)
- [Managing Database Permissions](https://civis.zendesk.com/hc/en-us/articles/360047203032-Managing-Database-Permissions) (provides high-level guidance on user and group organization)

**Comment by hunterowens** [comment]
@ian-r-rose to review / close before next Thrusday's meeting or add additional questions.

**Comment by ian-r-rose** [comment]
Thanks for these @skomanduri, the docs are very helpful (in particular setting up an `ALTER DEFAULT PERMISSIONS` regime.

I think this can be closed, and I can open a new issue for myself to track setting up the appropriate permissions on our existing schemas.
