### ISSUE TITLE
Update socrata import to point at CityOfLosAngeles github org

### ISSUE THREAD

**Issue by ian-r-rose** [CityOfLosAngeles/aqueduct#349]
The Socrata import template still points at civis' private gh repo. We should verify that we have the most up-to-date version, and that the template points to it.

**Comment by hunterowens** [comment]
@snassef is the owner of the template script

**Comment by snassef** [comment]
Hi - sorry was OOO last week. Template script has been updated to point to Aqueduct. I tested the import and everything looks good!

**Comment by ian-r-rose** [comment]
Thanks @snassef !
