### ISSUE TITLE
It's possible that the dockless ETL task is missing trips

### ISSUE THREAD

**Issue by ezheidtmann** [CityOfLosAngeles/aqueduct#46]
Hey there,

I've been tracking down an issue with MDS 0.2.x and just wanted to make sure you were aware that non-overlapping query windows on the MDS `trips` endpoint will result in missed trips. The `dockless_elt` task in this repo appears to do polling on 12 hour windows; if it's only run every 12 hours then there could be trouble. If the task is running twice as often (every 6 hours), you're probably fine.

I shared an example of the problem in the `mds-provider-services` repo: https://github.com/CityofSantaMonica/mds-provider-services/issues/20#issuecomment-447015877

The underlying issue is [already fixed in MDS 0.3.x](https://github.com/CityOfLosAngeles/mobility-data-specification/pull/139); just wanted to make sure that other consumers are compensating appropriately until all providers update to 0.3.x or provide other workarounds. 

All the best from your neighbor to the north,
Evan

**Comment by hunterowens** [comment]
@ezheidtmann 

this task is run hourly, as you can see in the DAG. Closing this issue for now. Thanks for the heads up.

**Comment by ezheidtmann** [comment]
👍 I couldn't find the schedule when I looked for it, but I see it now! Glad you're not affected.
