### ISSUE TITLE
Debugging long waze dag task runs

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/aqueduct#56]
Right now

* Airflow Scheduler only starts task every 15 minutes, should be starting every minute to process S3 bucket data. 
* Concurrency is set to 3 and seems to be working 
* Task takes about a minute to run, then lag until next task starts.

**Comment by bryanblackford** [comment]
My current plan is to reduce the dag to a single task that grabs the first unprocessed file from S3 (the S3 file check task doesn't add much) and then moves the processed file to the processed bucket. This will streamline the task, hopefully reducing overhead delays, and allow each task run to process multiple files, which will help us to stay caught up with the latest data.
