### ISSUE TITLE
Deploying aqueduct

### ISSUE THREAD

**Issue by ian-r-rose** [CityOfLosAngeles/aqueduct#80]
The current setup is kind of flaky. We are exploring a number of ways to improve it, including:

1. Using the official dockerfile and deploying it on EC2
1. Using the airflow helm chart on our kubernetes cluster
1. Managed airflow using Google Cloud Composer

Considerations:
* Can we use the existing backing mysql database to keep our history?
* What does our code deploy setup look like under different deployment strategies?

**Comment by ian-r-rose** [comment]
Another thought: we may want to separate repos for deployment configuration and DAGs.

**Comment by ian-r-rose** [comment]
Some more experiments:
* I have successfully deployed airflow on Kubernetes using our GKE cluster. It currently doesn't do much.
* We will want to nail down a docker image for our scheduler and worker pods, probably deriving from the default but adding some new python libs (as the current aqueduct does).
* What python libs do we want installed on the scheduler/worker pods? It seems reasonable to have a basic set of analysis libraries, but I think a kitchen-sink approach would probably end in tears. Super complicated jobs may be better run using a `KubernetesPodOperator`.
* We can have a git repo for DAGs that is automatically cloned when the scheduler pod is launched. We can also rsync the repo whenever a PR is merged in that repo. This speaks to probably having a different repo for deployment and dags.
* We'll need to figure out how to connect to the existing MySQL database, but can probably defer that until further down the road.

**Comment by ian-r-rose** [comment]
An update on this. We have been limping along with the current deployment, but there are some issues that should be addressed to make it more maintainable. I'll open those separately.

**Comment by ian-r-rose** [comment]
A discussion on an official Airflow docker image: https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-26+Production-ready+Airflow+Docker+Image+and+helm+chart, which currently does not exist.

**Comment by hunterowens** [comment]
closing in favor of migrating away from airflow.
