### ISSUE TITLE
Don't include airflow in requirements.txt

### ISSUE THREAD

**Issue by ian-r-rose** [CityOfLosAngeles/aqueduct#86]
Our codedeploy currently upgrades all packages in `requirements.txt` upon merging to master. This can trigger an upgrade to airflow, which can leave us with a mis-versioned backing DB. This is dangerous, and can lead to uncontrolled database migrations.

Long-term, this should be fixed by using a managed airflow, and by using more containerised solutions like `KubernetesPodOperator`. For the time being, let's not include airflow in the `requirements.txt` when adding/upgrading python packages.

cc @hunterowens

**Comment by hunterowens** [comment]
I think this just means we need to include airflow somewhere in the `Dockerfile`, but otherwise, SGTM
