### ISSUE TITLE
metro ridership dag returns success but I don't think it actually runs

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/aqueduct#89]
or at least, no log file...

**Comment by ian-r-rose** [comment]
I think I made the mistake of setting the start date in the future: https://github.com/CityOfLosAngeles/aqueduct/blob/961ab3407b22dc52f7d99552f3105186d39f0130/dags/tmf/metro/ridership.py#L182

Since Nov. 1st is so close, I had planned to just wait and see if it resolves itself.

**Comment by ian-r-rose** [comment]
This is now fixed by running after 10-30-19, and by fixing permissions issues on writing temporary files.
