### ISSUE TITLE
Upstream Bolt Auth

### ISSUE THREAD

**Issue by ian-r-rose** [CityOfLosAngeles/aqueduct#93]
In #92 we created a custom Bolt authenticator. We should extract that and make a PR against `mds-provider` with that authenticator. cc @RMK0110 .

**Comment by ian-r-rose** [comment]
Work-in progress in https://github.com/CityofSantaMonica/mds-provider/pull/85

**Comment by ian-r-rose** [comment]
Now that CityofSantaMonica/mds-provider#85 has been merged, we should remove the Bolt authenticator from this repository. cc @RMK0110

**Comment by hunterowens** [comment]
We'll have to untag / upgrade mds-provider in requirements.txt

**Comment by RMK0110** [comment]
> 
> 
> Now that [CityofSantaMonica/mds-provider#85](https://github.com/CityofSantaMonica/mds-provider/pull/85) has been merged, we should remove the Bolt authenticator from this repository. cc @RMK0110

bolt_auth was removed from their system.

**Comment by ian-r-rose** [comment]
No, it's still here: https://github.com/CityOfLosAngeles/aqueduct/blob/9cb1fc23330f9b5a2a580f87e2d58fe356c80fa4/dags/transportation/dockless/dockless_elt.py#L110-L144

**Comment by RMK0110** [comment]
The bolt authenticator class was removed in a recent push.
